add scopes and validations
Vadzimz/test-guru pull request #28
Opened 2024-12-05 16:48 UTC by Vadzimz

2024-12-05 17:03 UTC, BubuntuClu requested changes

2024-12-05 17:03 UTC, BubuntuClu commented on app/models/test.rb
> +  scope :selected_by_category, -> (category_title) { joins(:category).where(categories: {title: category_title}).order(title: :desc).pluck(:title) }
сортировку и выборку не надо помещать в скоуп.
скоуп должен возвращать объект ActiveRecord::Relation, pluck возвращает массив.
так же скоуп это универсальный метод, который может использован в разных частях приложения, там может потребоваться другая сортировка и выборка.

2024-12-05 17:03 UTC, BubuntuClu commented on app/models/test.rb
> +      Category.find_by!(title: category_title).tests.order(title: :desc).pluck(:title)
почему `find_by!`? что будет если такой категории нет в БД? тут лучше использовать скоуп, в котором ты  джойнишь тесты и категории, фильтруешь по названию категории и к результату скоупа применить сортировку с выборкой

2024-12-05 17:03 UTC, BubuntuClu commented on app/models/test.rb
> +  validates :title, presence: true, uniqueness: { scope: :level }
ограничения надо дублировать на всех уровнях приложения. можно через СУБД насоздавать данных, которые для приложения не будут валидны. в БД добавить уникальный составной индекс надо

2024-12-07 14:41 UTC, Vadzimz commented on app/models/question.rb
> +  validates :answers, length: { in: 1..4 }
Получается, что валидация требуется для ответа, на не вопроса

2024-12-07 16:41 UTC, merged