Add ORM lessons changes
Vadzimz/test-guru pull request #7
Opened 2024-09-20 18:29 UTC by Vadzimz

2024-09-21 17:33 UTC, BubuntuClu requested changes

2024-09-21 17:33 UTC, BubuntuClu commented on db/migrate/20240920134508_create_tests.rb
> +
не хватает внешнего ключа к табблице категорий. через `t.references` его указать можно

2024-09-21 17:33 UTC, BubuntuClu commented on db/migrate/20240920134716_create_questions.rb
> +      t.integer :testid
это надо создать через внешний ключ, а не просто колонку. и чтобы рельса понимала что ты хочешь от нее надо использовать соглашения в нейминге колонок. для связей используется такой формат сущностьвединственномчисле_id - `test_id`

2024-09-21 17:33 UTC, BubuntuClu commented on db/migrate/20240920134804_create_answers.rb
> +      t.integer :questionid
тоже самое что в вопросах

2024-09-29 17:53 UTC, BubuntuClu commented on db/migrate/20240920175932_add_some_null_constraints.rb
> +class AddSomeNullConstraints < ActiveRecord::Migration[7.2]
лишняя миграция, ты ведь указал при создании таблиц все

2024-09-29 17:53 UTC, BubuntuClu commented on db/migrate/20240920180943_add_some_default_values.rb
> +class AddSomeDefaultValues < ActiveRecord::Migration[7.2]
лишняя миграция, ты ведь указал при создании таблиц все

2024-09-30 17:38 UTC, Vadzimz commented on db/migrate/20240920175932_add_some_null_constraints.rb
> +class AddSomeNullConstraints < ActiveRecord::Migration[7.2]
Они у меня были в первой версии. Я откатился на 0, дополнил все create, и потом перешел на уровень до всех лишних миграций. То есть они у меня отключены. Их нужно удалить? А если, да, то можно просто удалить эти файлы с миграциями?

2024-11-25 14:39 UTC, merged